### ISSUE TITLE
unsupported operand

### ISSUE THREAD

**Issue by tpackolus** [KaushalBajaj11/GEC--Grammatical-Error-Correction#1]
Hi 

I have error TypeError: unsupported operand type(s) for +: 'int' and 'str'

can u help me ?

`test = validation[:1000]
bleu_score = 0
for i,j in zip(test['encoder_input'],test['decoder_output']):
    bleu_score = bleu_score + predict(i,j,40,model)
bleu_score = bleu_score/1000`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [45], in <cell line: 3>()
      2 bleu_score = 0
      3 for i,j in zip(test['encoder_input'],test['decoder_output']):
----> 4     bleu_score = bleu_score + predict(i,j,40,model)
      5 bleu_score = bleu_score/1000

TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by KaushalBajaj11** [comment]
Please try this:

total_bleu=0
for i,j in zip(test['encoder_input'],test['decoder_output']):
    pred = predict(i,j,40,model)
    correct = j.split()
    pred = pred.split()
    bleu_score = sentence_bleu([correct],pred,smoothing_function=smoothie)
    print('Real Output : {}'.format(j))
    print('Bleu Score for Correction : {}'.format(bleu_score))
